name: Steam_Idle_War_Thunder
on:
  workflow_dispatch:

jobs:
  run_idle:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Simple Script
        run: git clone https://github.com/jayme-github/steam_idle.git .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Steam Lib
        run: pip install steam[client]

      - name: Run
        env:
          STEAM_USER: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASS: ${{ secrets.STEAM_PASSWORD }}
        run: python3 main.py "$STEAM_USER" "$STEAM_PASS" 236390
